name: Run ftToMDX every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bun-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FT_API_KEY: ${{ secrets.FT_API_KEY }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run ftToMDX script
        run: bun src/automation/ftToMDX.ts

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update MDX posts"
